/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Clases.PlayWave;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author UTNG
 */
public class FrmPrincipal extends javax.swing.JFrame {
    /**
     * 
     */
    private JLabel[] tablero = new JLabel[16];
    private int[] datos = new int[16];
    private int pos1;
    private int pos2;
    private boolean banClick;
    private int tipo;   //0=libre, 1=tradicional
    private int disponible; //casilla vacia en tipo tradicional
    private JLabel lblTempo = new JLabel();
    private boolean banInicio; //true:ya inició el juego, 
    //false: aun no inicia el juego

    private AcercaDe acercaDe;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen01 = new javax.swing.JLabel();
        lblImagen02 = new javax.swing.JLabel();
        lblImagen03 = new javax.swing.JLabel();
        lblImagen04 = new javax.swing.JLabel();
        lblImagen08 = new javax.swing.JLabel();
        lblImagen07 = new javax.swing.JLabel();
        lblImagen06 = new javax.swing.JLabel();
        lblImagen05 = new javax.swing.JLabel();
        lblImagen12 = new javax.swing.JLabel();
        lblImagen11 = new javax.swing.JLabel();
        lblImagen10 = new javax.swing.JLabel();
        lblImagen09 = new javax.swing.JLabel();
        lblImagen16 = new javax.swing.JLabel();
        lblImagen15 = new javax.swing.JLabel();
        lblImagen14 = new javax.swing.JLabel();
        lblImagen13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbImagenes = new javax.swing.JComboBox<>();
        btnMezclar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Puzzle Soria 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        lblImagen01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen01MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblImagen02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a2.jpg"))); // NOI18N
        lblImagen02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen02MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen02, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        lblImagen03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a3.jpg"))); // NOI18N
        lblImagen03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen03MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen03, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblImagen04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a4.jpg"))); // NOI18N
        lblImagen04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen04MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen04, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        lblImagen08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a8.jpg"))); // NOI18N
        lblImagen08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen08MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen08, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        lblImagen07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a7.jpg"))); // NOI18N
        lblImagen07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen07MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen07, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        lblImagen06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a6.jpg"))); // NOI18N
        lblImagen06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen06MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen06, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        lblImagen05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a5.jpg"))); // NOI18N
        lblImagen05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen05MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen05, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblImagen12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a12.jpg"))); // NOI18N
        lblImagen12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen12MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        lblImagen11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a11.jpg"))); // NOI18N
        lblImagen11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen11MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        lblImagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.jpg"))); // NOI18N
        lblImagen10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen10MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        lblImagen09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a9.jpg"))); // NOI18N
        lblImagen09.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen09MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen09, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lblImagen16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a16.jpg"))); // NOI18N
        lblImagen16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen16MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        lblImagen15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a15.jpg"))); // NOI18N
        lblImagen15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen15MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        lblImagen14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a14.jpg"))); // NOI18N
        lblImagen14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen14MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        lblImagen13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a13.jpg"))); // NOI18N
        lblImagen13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen13MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Imágenes:");

        cmbImagenes.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        cmbImagenes.setForeground(new java.awt.Color(153, 0, 153));
        cmbImagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android", "Mike & Dave", "Sombrerero", "Payaso", "Bichos", "Dinosaurio" }));
        cmbImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImagenesActionPerformed(evt);
            }
        });

        btnMezclar.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        btnMezclar.setForeground(new java.awt.Color(153, 0, 153));
        btnMezclar.setText("Mezclar");
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });

        btnCreditos.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(153, 0, 153));
        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(153, 0, 153));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cmbTipo.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        cmbTipo.setForeground(new java.awt.Color(153, 0, 153));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Tradicional" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PUZZLE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbImagenes, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMezclar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMezclar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tablero[0] = lblImagen01;
        tablero[1] = lblImagen02;
        tablero[2] = lblImagen03;
        tablero[3] = lblImagen04;
        tablero[4] = lblImagen05;
        tablero[5] = lblImagen06;
        tablero[6] = lblImagen07;
        tablero[7] = lblImagen08;
        tablero[8] = lblImagen09;
        tablero[9] = lblImagen10;
        tablero[10] = lblImagen11;
        tablero[11] = lblImagen12;
        tablero[12] = lblImagen13;
        tablero[13] = lblImagen14;
        tablero[14] = lblImagen15;
        tablero[15] = lblImagen16;

        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed
        // TODO add your handling code here:
        Random r1 = new Random();
        int x;
        if (tipo == 0) {
            for (int i = 1; i < 100; i++) {
                x = r1.nextInt(16);
                seleccionar(x);
            }
        } else if (tipo == 1) {
            for (int i = 1; i <= 1000; i++) {
                x = r1.nextInt(16);
                mover(x);
                //          seleccionar(x);

            }
        }
        //banPlay = true;
        banInicio = true;

    }//GEN-LAST:event_btnMezclarActionPerformed

    private void lblImagen01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen01MouseClicked
        // TODO add your handling code here:
        tirar(0);
    }//GEN-LAST:event_lblImagen01MouseClicked

    private void lblImagen02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen02MouseClicked
        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImagen02MouseClicked

    private void lblImagen03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen03MouseClicked
        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImagen03MouseClicked

    private void lblImagen04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen04MouseClicked
        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImagen04MouseClicked

    private void lblImagen05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen05MouseClicked
        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImagen05MouseClicked

    private void lblImagen06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen06MouseClicked
        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImagen06MouseClicked

    private void lblImagen07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen07MouseClicked
        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImagen07MouseClicked

    private void lblImagen08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen08MouseClicked
        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImagen08MouseClicked

    private void lblImagen09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen09MouseClicked
        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImagen09MouseClicked

    private void lblImagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen10MouseClicked
        // TODO add your handling code here:
        tirar(9);
    }//GEN-LAST:event_lblImagen10MouseClicked

    private void lblImagen11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen11MouseClicked
        // TODO add your handling code here:
        tirar(10);
    }//GEN-LAST:event_lblImagen11MouseClicked

    private void lblImagen12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen12MouseClicked
        // TODO add your handling code here:
        tirar(11);
    }//GEN-LAST:event_lblImagen12MouseClicked

    private void lblImagen13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen13MouseClicked
        // TODO add your handling code here:
        tirar(12);
    }//GEN-LAST:event_lblImagen13MouseClicked

    private void lblImagen14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen14MouseClicked
        // TODO add your handling code here:
        tirar(13);
    }//GEN-LAST:event_lblImagen14MouseClicked

    private void lblImagen15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen15MouseClicked
        // TODO add your handling code here:
        tirar(14);
    }//GEN-LAST:event_lblImagen15MouseClicked

    private void lblImagen16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen16MouseClicked
        // TODO add your handling code here:
        tirar(15);
    }//GEN-LAST:event_lblImagen16MouseClicked

    private void cmbImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImagenesActionPerformed
        // TODO add your handling code here:
        banInicio = false; //requiere mezclarse para iniciar
        disponible = 15;
        //se inicializan los datos
        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
        //poniendo borde a las piezas del tablero
        for (int i = 0; i < 16; i++) {
            tablero[i].setBorder(new LineBorder(Color.black, 1));
        }
        int op;
        op = cmbImagenes.getSelectedIndex();
        switch (op) {
            case 0:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/a1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/a2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/a3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/a4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/a5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/a6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/a7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/a8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/a9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/a10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/a11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/a12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/a13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/a14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/a15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/a16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
                }
                break;
            case 1:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/m_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
                }
                break;
            case 2:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/s1.png")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/s2.png")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/s3.png")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/s4.png")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/s5.png")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/s6.png")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/s7.png")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/s8.png")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/s9.png")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/s10.png")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/s11.png")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/s12.png")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/s13.png")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/s14.png")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/s15.png")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/s16.png")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
                }
                break;
            case 3:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/p1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/p2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/p3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/p4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/p5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/p6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/p7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/p8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/p9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/p10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/p11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/p12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/p13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/p14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/p15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/p16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
                }
                break;
            case 4:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/b_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
                }
                break;
            case 5:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/d_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
                }
                break;
        }
    }//GEN-LAST:event_cmbImagenesActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:

        tipo = cmbTipo.getSelectedIndex();
        if (tipo == 0) {    //libre
            // ...
        } else if (tipo == 1) {  //clasico
            lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/holi.jpg")));
            disponible = 15;
        }
        this.cmbImagenesActionPerformed(null);
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas salir?");
        if (JOptionPane.OK_OPTION == res) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        acercaDe = new AcercaDe();
        acercaDe.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        sonidoFondo();
    }//GEN-LAST:event_formWindowActivated
    public void sonidoFondo() {
        try {
            PlayWave pw1;
            URL ur1 = getClass().getResource("/media/fondo.wav");
            pw1 = new PlayWave(ur1);
            pw1.start();
        } catch (URISyntaxException e) {
            System.out.println(" Error en la URL!! ");
        }
    }

    private boolean esValidoMov(int pos) {
        boolean salida = false;
        int dx; //Fila del disponible
        int dy; //Columna del disponible
        int posx; //fila de posicion a vereficar
        int posy; //columna de posicion a verificar
        dx = disponible / 4;
        dy = disponible % 4;
        posx = pos / 4;
        posy = pos % 4;
        if (dx == posx) { //misma fila
            if (Math.abs(disponible - pos) == 1) {
                salida = true;
            }
        }
        if (dy == posy) { //misma columna
            if (Math.abs(disponible - pos) == 4) {
                salida = true;
            }
        }
        return salida;
    }

    private void seleccionar(int pos) {

        if (!banClick) {    //primer click
            pos1 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 1));
            banClick = true;
        } else {
            pos2 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
            banClick = false;
            intercambiar(pos1, pos2);

        }
    }

    private void intercambiar(int pos1, int pos2) {
        //Intercambio de imagenes de la posición
        JLabel lblTempo = new JLabel();
        lblTempo.setIcon(tablero[pos1].getIcon());
        tablero[pos1].setIcon(tablero[pos2].getIcon());
        tablero[pos2].setIcon(lblTempo.getIcon());
        int tempo;
        tempo = datos[pos1];
        datos[pos1] = datos[pos2];
        datos[pos2] = tempo;
    }

    private void revisar() {
        if (banInicio && !banClick && verificar()) {
            JOptionPane.showMessageDialog(this, "Ya ganaste!");
            cmbTipo.setSelectedIndex(0);
            tipo = 0;
            //banPlay= false;
            for (int i = 0; i < 16; i++) {
                tablero[i].setBorder(null);
            }
            banInicio = false;
        }
    }

    /**
     * Verifica si ya ganó, es decir si el rompecabezas ya esta armado
     * correctamente.
     *
     * @return true= ya ganó, false= no ha ganado.
     */
    private boolean verificar() {
        for (int i = 0; i < 16; i++) {
            if (datos[i] != i) {
                return false;
            }
        }
        return true;
    }

    public void mover(int pos) {
        if (banInicio) {
            if (tipo == 0) {
                seleccionar(pos);
            } else if (tipo == 1) {
                if (esValidoMov(pos)) {
                    intercambiar(pos, disponible);
                    disponible = pos;
                }
            }
        }
    }

    private void moverLinea(int pos) {
        if (banInicio) {
//            if (tipo == 2) {
//                lblTempo.setIcon(tablero[0].getIcon());
//                disponible = 0;
//                pos = 12;
//            }
            if (pos / 4 == disponible / 4) { //pertenecen a la misma fila
                if (pos > disponible) { //esta a la derecha
                    for (int i = disponible + 1; i <= pos; i++) {
                        mover(i);
                    }
                } else {
                    for (int i = disponible - 1; i >= pos; i--) {
                        mover(i);
                    }

                }
            } else if (pos % 4 == disponible % 4) {// misma columna
                if (pos > disponible) {// esta abajo 
                    for (int i = disponible + 4; i <= pos; i = i + 4) {
                        mover(i);
                    }
                } else {
                    for (int i = disponible - 4; i >= pos; i = i - 4) {
                        mover(i);
                    }
                }
            }
        }
    }

    public void tirar(int pos) {
        if (tipo == 0) {
            mover(pos);
        } else if (tipo == 1) {
            moverLinea(pos);
        }
        revisar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnMezclar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbImagenes;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen01;
    private javax.swing.JLabel lblImagen02;
    private javax.swing.JLabel lblImagen03;
    private javax.swing.JLabel lblImagen04;
    private javax.swing.JLabel lblImagen05;
    private javax.swing.JLabel lblImagen06;
    private javax.swing.JLabel lblImagen07;
    private javax.swing.JLabel lblImagen08;
    private javax.swing.JLabel lblImagen09;
    private javax.swing.JLabel lblImagen10;
    private javax.swing.JLabel lblImagen11;
    private javax.swing.JLabel lblImagen12;
    private javax.swing.JLabel lblImagen13;
    private javax.swing.JLabel lblImagen14;
    private javax.swing.JLabel lblImagen15;
    private javax.swing.JLabel lblImagen16;
    // End of variables declaration//GEN-END:variables
}
